packages:
  - "apps/vi_VN/account"
  - "apps/vi_VN/author"
  - "apps/vi_VN/bbs"
  - "apps/vi_VN/bps"
  - "apps/vi_VN/dashboard"
  - "apps/vi_VN/event"
  - "apps/vi_VN/fb"
  - "apps/vi_VN/index"
  - "apps/vi_VN/macro"
  - "apps/vi_VN/publish"
  - "apps/vi_VN/pvp"
  - "apps/vi_VN/pvx"
  - "apps/vi_VN/search"
  - "apps/vi_VN/tinymce"
  - "apps/vi_VN/tool"
  - "apps/vi_VN/topic"
  - "apps/vi_VN/wiki"
  # shared libs
  - "packages/vi_VN/jx3box-bmap"
  - "packages/vi_VN/jx3box-build-common"
  - "packages/vi_VN/jx3box-comment-ui"
  - "packages/vi_VN/jx3box-common"
  - "packages/vi_VN/jx3box-common-ui"
  - "packages/vi_VN/jx3box-data"
  - "packages/vi_VN/jx3box-dict"
  - "packages/vi_VN/jx3box-editor"
  - "packages/vi_VN/jx3box-emotion"
  - "packages/vi_VN/jx3box-facedat"
  - "packages/vi_VN/jx3box-macro"
  - "packages/vi_VN/jx3box-map"
  - "packages/vi_VN/jx3box-petmap"
  - "packages/vi_VN/jx3box-talent"
  - "packages/vi_VN/jx3box-talent2"
  - "packages/vi_VN/jx3box-vue3-ui"
  - "packages/vi_VN/markdown"
  - "packages/vi_VN/reporter/**"
  - "packages/vi_VN/tools/viteconfig"
