packages:
  # - "apps/account"
  - "apps/author"
  - "apps/bbs"
  - "apps/bps"
  # - "apps/dashboard"
  - "apps/event"
  - "apps/fb"
  - "apps/index"
  - "apps/macro"
  - "apps/publish"
  # - "apps/pvp"
  - "apps/pvx"
  - "apps/search"
  - "apps/tinymce"
  - "apps/tool"
  - "apps/topic"
  - "apps/wiki"
  # shared libs
  - "packages/jx3box-bmap"
  - "packages/jx3box-build-common"
  - "packages/jx3box-comment-ui"
  - "packages/jx3box-common"
  - "packages/jx3box-common-ui"
  - "packages/jx3box-data"
  - "packages/jx3box-dict"
  - "packages/jx3box-editor"
  - "packages/jx3box-emotion"
  - "packages/jx3box-facedat"
  - "packages/jx3box-macro"
  - "packages/jx3box-map"
  - "packages/jx3box-petmap"
  - "packages/jx3box-talent"
  - "packages/jx3box-talent2"
  - "packages/jx3box-vue3-ui"
  - "packages/markdown"
  - "packages/reporter/**"
  - "packages/tools/viteconfig"
