name: Node.js Package

on: [push]

# on:
#   release:
#     types: [created]

jobs:
  publish-npm:
    # needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      # - run: npm ci
      - name: Install && Build
        run: |
          npm install
          npm run build
          npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # publish-gpr:
  #   # needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - uses: actions/setup-node@v1
  #       with:
  #         node-version: 12
  #         registry-url: https://npm.pkg.github.com/
  #         scope: '@jx3box'
  #     - run: npm run build
  #     - run: npm publish
  #       env:
  #         NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: OSS&CDN
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: "oss-cn-hangzhou.aliyuncs.com"
          access-key-id: ${{secrets.AccessKey_ID}}
          access-key-secret: ${{secrets.Access_Key_Secret}}
      - run: ossutil cp -rf resources oss://jx3box/static/markdown

